const ACTION_ADD = 1;
const ACTION_INCREASE = 2;
const ACTION_DECREASE = 3;
const ACTION_REMOVE = 4;
const ACTION_CLEAR = 5;
const ACTION_FETCH = 8;

export {
  ACTION_ADD,
  ACTION_INCREASE,
  ACTION_DECREASE,
  ACTION_REMOVE,
  ACTION_CLEAR,
  ACTION_FETCH,
};
